In [1]:
import MetaTrader5 as mt5
import pandas as pd
from peaks import calculate_peak,print_horario,full_table
import warnings
warnings.filterwarnings("ignore")

if not mt5.initialize(path = r'C:\Program Files\Zero Markets MetaTrader 5 Terminal\terminal64.exe'):
    print("initialize() failed")
    mt5.shutdown()

In [2]:
ativo = 'EURUSD.r'
df = pd.DataFrame(mt5.copy_rates_from_pos(ativo, mt5.TIMEFRAME_M1, 0, 40000))
df['Data'] = pd.to_datetime(df['time'], unit='s').apply(lambda x: str(x))
df = df[['Data','open','high','low','close','real_volume']]
df.columns = ['Data','Open','High','Low','Close','Vol']
df = df.rename(columns = {'real_volume':'vol'})
#df['RSI'] = ta.RSI(df['Close'],timeperiod = 14)

In [3]:
new_total = None
dist = 2
for tam_stop in [0.0002,0.0003,0.0005]:
    stats = calculate_peak(df,dist = 2,plot=False,tam_stop = tam_stop,valley = False)
    
    new = full_table(stats, dist = 1,tam_stop = tam_stop)

    new_total = pd.concat([new_total,new])

    print(new_total.to_string())

   Timeframe  Dist  Tam_stop  N_trades  Taxa_acerto  Pontos_total   Retorno
0          5     1    0.0002       179    47.486034      -0.00374 -0.345484
   Timeframe  Dist  Tam_stop  N_trades  Taxa_acerto  Pontos_total   Retorno
0          5     1    0.0002       179    47.486034      -0.00374 -0.345484
0          5     1    0.0003        84    45.238095      -0.00366 -0.340976
   Timeframe  Dist  Tam_stop  N_trades  Taxa_acerto  Pontos_total   Retorno
0          5     1    0.0002       179    47.486034      -0.00374 -0.345484
0          5     1    0.0003        84    45.238095      -0.00366 -0.340976
0          5     1    0.0005        25    36.000000      -0.00404 -0.374942

In [26]:
df

,Data,Open,High,Low,Close,Vol,signal,stop,tp,tamanho
0,2022-12-16 15:43:00,1.21840,1.21844,1.21825,1.21838,0,0,0.0,0.0,-1.21838
1,2022-12-16 15:44:00,1.21834,1.21848,1.21830,1.21840,0,0,0.0,0.0,-1.21840
2,2022-12-16 15:45:00,1.21839,1.21874,1.21823,1.21835,0,0,0.0,0.0,-1.21835
3,2022-12-16 15:46:00,1.21839,1.21847,1.21801,1.21802,0,0,0.0,0.0,-1.21802
4,2022-12-16 15:47:00,1.21802,1.21869,1.21802,1.21858,0,0,0.0,0.0,-1.21858
...,...,...,...,...,...,...,...,...,...,...
39995,2023-01-27 14:55:00,1.23688,1.23695,1.23655,1.23660,0,0,0.0,0.0,-1.23660
39996,2023-01-27 14:56:00,1.23659,1.23670,1.23650,1.23668,0,0,0.0,0.0,-1.23668
39997,2023-01-27 14:57:00,1.23667,1.23680,1.23646,1.23649,0,0,0.0,0.0,-1.23649
39998,2023-01-27 14:58:00,1.23652,1.23658,1.23643,1.23653,0,0,0.0,0.0,-1.23653
39999,2023-01-27 14:59:00,1.23657,1.23663,1.23656,1.23659,0,0,0.0,0.0,-1.23659